NorthCampus_PokeballResearchLab_MapScripts::
	.byte 0


NorthCampus_PokeballResearchLab_PokeBall::
# 4 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	msgbox NorthCampus_PokeballResearchLab_PokeBall_Text_0
	end


NorthCampus_PokeballResearchLab_PokeBall_Text_0:
# 4 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	.string "It's a model of a Poké Ball\nused for educational purposes.$"
