NorthCampus_PokeballResearchLab_MapScripts::
	.byte 0


NorthCampus_PokeballResearchLab_PokeBall::
# 4 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	msgbox NorthCampus_PokeballResearchLab_PokeBall_Text_0
# 5 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	closemessage
	end


NorthCampus_PokeballResearchLab_GreatBall::
# 10 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	msgbox NorthCampus_PokeballResearchLab_GreatBall_Text_0
# 11 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	closemessage
	end


NorthCampus_PokeballResearchLab_UltraBall::
# 16 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	msgbox NorthCampus_PokeballResearchLab_UltraBall_Text_0
# 17 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	closemessage
	end


NorthCampus_PokeballResearchLab_NetBall::
# 22 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	msgbox NorthCampus_PokeballResearchLab_NetBall_Text_0
# 23 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	closemessage
	end


NorthCampus_PokeballResearchLab_QuickBall::
# 28 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	msgbox NorthCampus_PokeballResearchLab_QuickBall_Text_0
# 29 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	closemessage
	end


NorthCampus_PokeballResearchLab_DuskBall::
# 34 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	msgbox NorthCampus_PokeballResearchLab_DuskBall_Text_0
# 35 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	closemessage
	end


NorthCampus_PokeballResearchLab_TimerBall::
# 40 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	msgbox NorthCampus_PokeballResearchLab_TimerBall_Text_0
# 41 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	closemessage
	end


NorthCampus_PokeballResearchLab_DiveaBall::
# 46 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	msgbox NorthCampus_PokeballResearchLab_DiveaBall_Text_0
# 47 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	closemessage
	end


NorthCampus_PokeballResearchLab_Laptops::
# 52 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	msgbox NorthCampus_PokeballResearchLab_Laptops_Text_0
# 53 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	closemessage
	end


NorthCampus_PokeballResearchLab_AceTrainerF::
# 58 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	lock
# 59 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	faceplayer
# 60 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	msgbox NorthCampus_PokeballResearchLab_AceTrainerF_Text_0
# 61 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	closemessage
# 62 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	release
	end


NorthCampus_PokeballResearchLab_Scientist::
# 67 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	lock
# 68 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	msgbox NorthCampus_PokeballResearchLab_Scientist_Text_0
# 69 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	closemessage
# 70 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	release
	end


NorthCampus_PokeballResearchLab_Boy::
# 75 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	lock
# 76 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	faceplayer
# 77 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	msgbox NorthCampus_PokeballResearchLab_Boy_Text_0
# 78 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	closemessage
# 79 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	release
	end


NorthCampus_PokeballResearchLab_SuperNerd::
# 84 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	lock
# 85 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	faceplayer
# 86 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	msgbox NorthCampus_PokeballResearchLab_SuperNerd_Text_0
# 87 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	closemessage
# 88 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	release
	end


NorthCampus_PokeballResearchLab_PokeBall_Text_0:
# 4 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	.string "An educational model of a Poké Ball.\p"
	.string "It's the most basic type of Poké Ball.$"

NorthCampus_PokeballResearchLab_GreatBall_Text_0:
# 10 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	.string "An educational model of a Great Ball.\pIt's 1.5x more effective than a Poké Ball.$"

NorthCampus_PokeballResearchLab_UltraBall_Text_0:
# 16 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	.string "An educational model of an Ultra Ball.\pIt's 2x more effective than a Poké Ball.$"

NorthCampus_PokeballResearchLab_NetBall_Text_0:
# 22 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	.string "An educational model of a Net Ball.\pIt's 2x more effective than a Poké Ball on {COLOR RED}Water- {COLOR DARK_GRAY}and {COLOR RED}Bug-type {COLOR DARK_GRAY}Pokémon.$"

NorthCampus_PokeballResearchLab_QuickBall_Text_0:
# 28 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	.string "An educational model of a Quick Ball.\pIt's 5x more effective than a Poké Ball when used at the start of a wild encounter.$"

NorthCampus_PokeballResearchLab_DuskBall_Text_0:
# 34 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	.string "An educational model of a Dusk Ball.\pIt's 3.5x more effective than a Poké Ball when used in dark places like caves or at night.$"

NorthCampus_PokeballResearchLab_TimerBall_Text_0:
# 40 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	.string "An educational model of a Timer Ball.\pIts effectiveness increases the longer the battle goes on, up to 4x.$"

NorthCampus_PokeballResearchLab_DiveaBall_Text_0:
# 46 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	.string "An educational model of a Dive Ball.\pIt's 2x more effective than a Poké Ball when used on Pokémon encountered while fishing or surfing.$"

NorthCampus_PokeballResearchLab_Laptops_Text_0:
# 52 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	.string "This laptop contains research data on\n"
	.string "various Poké Balls.\p"
	.string "Scientists are constantly working to\n"
	.string "improve Poké Ball technology!$"

NorthCampus_PokeballResearchLab_AceTrainerF_Text_0:
# 60 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	.string "There's so many different types of\n"
	.string "Poké Balls!\p"
	.string "I wonder which one is the best…$"

NorthCampus_PokeballResearchLab_Scientist_Text_0:
# 68 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	.string "Let's see…\p"
	.string "Carry the one…\n"
	.string "Set the capture rates…\p"
	.string "No, no, that's not right!\n"
	.string "My mathematics are all off today!$"

NorthCampus_PokeballResearchLab_Boy_Text_0:
# 77 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	.string "I want to be an amazing Pokémon Trainer\n"
	.string "someday!\p"
	.string "I think I'll start by learning all about\n"
	.string "Poké Balls!$"

NorthCampus_PokeballResearchLab_SuperNerd_Text_0:
# 86 "data/maps/NorthCampus_PokeballResearchLab/scripts.pory"
	.string "Did you know that Poké Balls were\n"
	.string "originally crafted by hand by carving\l"
	.string "out {COLOR GREEN}Apricorns{COLOR DARK_GRAY}?\p"
	.string "Modern Poké Balls are made using\n"
	.string "high-tech machinery, but the basic\l"
	.string "design has remained the same!\p"
	.string "I hear there's a man in Johto who still\n"
	.string "makes Poké Balls the old-fashioned\l"
	.string "way!$"
