NorthCampus_PokemonMart_MapScripts::
	.byte 0


NorthCampus_PokemonMart_NPC1::
# 4 "data/maps/NorthCampus_PokemonMart/scripts.pory"
	lock
# 5 "data/maps/NorthCampus_PokemonMart/scripts.pory"
	faceplayer
# 6 "data/maps/NorthCampus_PokemonMart/scripts.pory"
	msgbox NorthCampus_PokemonMart_NPC1_Text_0
# 7 "data/maps/NorthCampus_PokemonMart/scripts.pory"
	closemessage
# 8 "data/maps/NorthCampus_PokemonMart/scripts.pory"
	release
	end


NorthCampus_PokemonMart_NPC1_Text_0:
# 6 "data/maps/NorthCampus_PokemonMart/scripts.pory"
	.string "{COLOR GREEN}Awakenings{COLOR DARK_GRAY} are so useful.\p"
	.string "I hate when my Pokémon is put to sleep\n"
	.string "in the middle of a battle!$"
