#ifndef GUARD_CONSTANTS_SPEAKER_NAMES_H
#define GUARD_CONSTANTS_SPEAKER_NAMES_H

enum SpeakerNames {
    SP_NAME_NONE = 0,
    SP_NAME_MOM,
    SP_NAME_PLAYER,
    SP_NAME_UNKNOWN,
    SP_NAME_TRACIE,
    SP_NAME_ROTCART,
    SP_NAME_MAPLE,
    SP_NAME_MAN,
    SP_NAME_LASS,
    SP_NAME_YOUNGSTER,
    SP_NAME_NURSE_JOY,
    SP_NAME_RECEPTIONIST,
    SP_NAME_CELESTE,
    SP_NAME_GABE,
    SP_NAME_BERTIE,
    SP_NAME_COLTON,
    SP_NAME_BUCK,
    SP_NAME_COUNT
};

#endif // GUARD_CONSTANTS_SPEAKER_NAMES_H
