gText_ObtainedTheItem::
	.string "Obtained the {COLOR GREEN}{STR_VAR_2}{COLOR DARK_GRAY}!$"

gText_TheBagIsFull::
	.string "The Bag is full…$"

gText_PutItemInPocket::
	.string "{PLAYER} put away the {COLOR GREEN}{STR_VAR_2}\n"
	.string "{COLOR DARK_GRAY}in the {STR_VAR_3} Pocket.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} found one {COLOR GREEN}{STR_VAR_2}{COLOR DARK_GRAY}!$"

gText_TooBadBagIsFull::
	.string "Too bad!\n"
	.string "The Bag is full…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} put away the {COLOR GREEN}{STR_VAR_2}\n"
	.string "{COLOR DARK_GRAY}in the Bag.$"

gText_ObtainedTheDecor::
	.string "Obtained the {COLOR GREEN}{STR_VAR_2}{COLOR DARK_GRAY}!$"

gText_NoRoomLeftForAnother::
	.string "Too bad! There's no room left for\n"
	.string "another {COLOR GREEN}{STR_VAR_2}{COLOR DARK_GRAY}…$"

gText_TheDecorWasTransferredToThePC::
	.string "The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"

gText_ObtainedTheItems::
	.string "Obtained {COLOR GREEN}{STR_VAR_1} {STR_VAR_2}{COLOR DARK_GRAY}!$"

gText_PlayerFoundItems::
	.string "{PLAYER} found {STR_VAR_1} {STR_VAR_2}!$"

gText_PutCoinsAwayInCoinCase::
	.string "{PLAYER} put the COINS away in\n"
	.string "the COIN CASE.$"

gText_FoundXCoins::
	.string "{PLAYER} found\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

gText_FoundXItems::
	.string "{PLAYER} found\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)!$"

gText_CoinCaseIsFull::
	.string "Too bad!\n"
	.string "The COIN CASE is full…$"

gText_NothingToPutThemIn::
	.string "Too bad!\n"
	.string "There's nothing to put them in…$"
