NorthCampus_Classroom3_MapScripts::
	.byte 0


NorthCampus_Classroom3_NPC1::
# 4 "data/maps/NorthCampus_Classroom3/scripts.pory"
	lock
# 5 "data/maps/NorthCampus_Classroom3/scripts.pory"
	faceplayer
# 6 "data/maps/NorthCampus_Classroom3/scripts.pory"
	msgbox NorthCampus_Classroom3_NPC1_Text_0
# 7 "data/maps/NorthCampus_Classroom3/scripts.pory"
	closemessage
# 8 "data/maps/NorthCampus_Classroom3/scripts.pory"
	release
	end


NorthCampus_Classroom3_NPC2::
# 13 "data/maps/NorthCampus_Classroom3/scripts.pory"
	lock
# 14 "data/maps/NorthCampus_Classroom3/scripts.pory"
	faceplayer
# 15 "data/maps/NorthCampus_Classroom3/scripts.pory"
	msgbox NorthCampus_Classroom3_NPC2_Text_0
# 16 "data/maps/NorthCampus_Classroom3/scripts.pory"
	closemessage
# 17 "data/maps/NorthCampus_Classroom3/scripts.pory"
	release
	end


NorthCampus_Classroom3_NPC1_Text_0:
# 6 "data/maps/NorthCampus_Classroom3/scripts.pory"
	.string "Ugh, this class is hard.\n"
	.string "I have to actually study!$"

NorthCampus_Classroom3_NPC2_Text_0:
# 15 "data/maps/NorthCampus_Classroom3/scripts.pory"
	.string "DHave you taken Water Pokémon Habits\n"
	.string "and Habitats?\p"
	.string "It's my favorite class so far!\p"
	.string "Next to Famous Fishing Folk Fables,\n"
	.string "that is.$"
