NorthCampus_Classroom1_MapScripts::
	.byte 0


NorthCampus_Classroom1_NPC1::
# 4 "data/maps/NorthCampus_Classroom1/scripts.pory"
	lock
# 5 "data/maps/NorthCampus_Classroom1/scripts.pory"
	faceplayer
# 6 "data/maps/NorthCampus_Classroom1/scripts.pory"
	msgbox NorthCampus_Classroom1_NPC1_Text_0
# 7 "data/maps/NorthCampus_Classroom1/scripts.pory"
	closemessage
# 8 "data/maps/NorthCampus_Classroom1/scripts.pory"
	release
	end


NorthCampus_Classroom1_NPC1_Text_0:
# 6 "data/maps/NorthCampus_Classroom1/scripts.pory"
	.string "My goal is to collect every kind of\n"
	.string "Pokémon you can find around the school\l"
	.string "before I leave on my journey.$"
