NorthCampus_Classroom2_MapScripts::
	.byte 0


NorthCampus_Classroom2_NPC1::
# 4 "data/maps/NorthCampus_Classroom2/scripts.pory"
	lock
# 5 "data/maps/NorthCampus_Classroom2/scripts.pory"
	faceplayer
# 6 "data/maps/NorthCampus_Classroom2/scripts.pory"
	msgbox NorthCampus_Classroom2_NPC1_Text_0
# 7 "data/maps/NorthCampus_Classroom2/scripts.pory"
	closemessage
# 8 "data/maps/NorthCampus_Classroom2/scripts.pory"
	release
	end


NorthCampus_Classroom2_NPC2::
# 13 "data/maps/NorthCampus_Classroom2/scripts.pory"
	lock
# 14 "data/maps/NorthCampus_Classroom2/scripts.pory"
	faceplayer
# 15 "data/maps/NorthCampus_Classroom2/scripts.pory"
	msgbox NorthCampus_Classroom2_NPC2_Text_0
# 16 "data/maps/NorthCampus_Classroom2/scripts.pory"
	closemessage
# 17 "data/maps/NorthCampus_Classroom2/scripts.pory"
	release
	end


NorthCampus_Classroom2_NPC1_Text_0:
# 6 "data/maps/NorthCampus_Classroom2/scripts.pory"
	.string "There was a time when {COLOR RED}Psychic-type\n"
	.string "{COLOR DARK_GRAY}Pokémon were considered to be the most\l"
	.string "powerful of all.\p"
	.string "Sadly, that time has passed…$"

NorthCampus_Classroom2_NPC2_Text_0:
# 15 "data/maps/NorthCampus_Classroom2/scripts.pory"
	.string "I have Professor Maple for Berry\n"
	.string "Blending 101.\p"
	.string "She's super nice!$"
