SouthCampus_Cafeteria_MapScripts::
	.byte 0


SouthCampus_Cafeteria_Waiter::
# 4 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	lock
# 5 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	faceplayer
# 6 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	msgbox SouthCampus_Cafeteria_Waiter_Text_0
# 7 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	closemessage
# 8 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	release
	end


SouthCampus_Cafeteria_Waitress::
# 13 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	lock
# 14 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	faceplayer
# 15 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	msgbox SouthCampus_Cafeteria_Waiter_Text_0
# 16 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	closemessage
# 17 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	release
	end


SouthCampus_Cafeteria_YoungCoupleF::
# 22 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	lock
# 23 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	faceplayer
# 24 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	msgbox SouthCampus_Cafeteria_YoungCoupleF_Text_0
# 25 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	closemessage
# 26 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	release
	end


SouthCampus_Cafeteria_YoungCoupleM::
# 31 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	lock
# 32 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	faceplayer
# 33 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	msgbox SouthCampus_Cafeteria_YoungCoupleM_Text_0
# 34 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	closemessage
# 35 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	release
	end


SouthCampus_Cafeteria_SchoolGirl::
# 40 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	lock
# 41 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	faceplayer
# 42 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	msgbox SouthCampus_Cafeteria_SchoolGirl_Text_0
# 43 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	closemessage
# 44 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	release
	end


SouthCampus_Cafeteria_AromaGirl::
# 49 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	lock
# 50 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	faceplayer
# 51 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	msgbox SouthCampus_Cafeteria_AromaGirl_Text_0
# 52 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	closemessage
# 53 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	release
	end


SouthCampus_Cafeteria_Guitarist::
# 58 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	lock
# 59 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	faceplayer
# 60 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	msgbox SouthCampus_Cafeteria_Guitarist_Text_0
# 61 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	closemessage
# 62 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	release
	end


SouthCampus_Cafeteria_Waiter_Text_0:
# 6 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	.string "Hello! Please, take a seat and enjoy!$"

SouthCampus_Cafeteria_YoungCoupleF_Text_0:
# 24 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	.string "My boyfriend and I met here at the\n"
	.string "cafeteria our freshman year.\p"
	.string "I don't think he realizes he's put on a\n"
	.string "few pounds…$"

SouthCampus_Cafeteria_YoungCoupleM_Text_0:
# 33 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	.string "Don't tell my girlfriend, but I think she\n"
	.string "may have gained weight from all the\l"
	.string "free food.$"

SouthCampus_Cafeteria_SchoolGirl_Text_0:
# 42 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	.string "I get the Chansey omelette every\n"
	.string "morning!\p"
	.string "Do you think it's giving me HP effort\n"
	.string "values?$"

SouthCampus_Cafeteria_AromaGirl_Text_0:
# 51 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	.string "With the ocean nearby, there's always a\n"
	.string "wide selection of seafood.\p"
	.string "Just last night, I had the Magikarp\n"
	.string "Piccata!$"

SouthCampus_Cafeteria_Guitarist_Text_0:
# 60 "data/maps/SouthCampus_Cafeteria/scripts.pory"
	.string "Sigh…\p"
	.string "My parents dropped me off this morning,\n"
	.string "but I actually flunked out last year.\p"
	.string "How am I going to tell them?$"
